### ISSUE TITLE
这个项目的运行环境是py2.7?

### ISSUE THREAD

**Issue by wujunze** [namco1992/lagou_crawler#1]
现在scrapy支持py3.5吗?

**Comment by namco1992** [comment]
是的，是我没写清楚，是在2.7环境下的。就1.1.0版本的文档来看，scrapy还是不支持py3，很遗憾。

**Comment by namco1992** [comment]
你可以在这里查看一下py3的支持情况。[https://github.com/scrapy/scrapy/wiki/Python-3-Porting](https://github.com/scrapy/scrapy/wiki/Python-3-Porting)

**Comment by wujunze** [comment]
OK  目前有什么爬虫框架支持py3.5吗?

**Comment by namco1992** [comment]
pyspider，还是国货，可以支持一下

**Comment by wujunze** [comment]
OK   3Q  可以close  这个issue了
